//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD.AMDPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double top {
            get {
                return ((double)(this["top"]));
            }
            set {
                this["top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double left {
            get {
                return ((double)(this["left"]));
            }
            set {
                this["left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double height {
            get {
                return ((double)(this["height"]));
            }
            set {
                this["height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double width {
            get {
                return ((double)(this["width"]));
            }
            set {
                this["width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public global::System.Windows.Visibility playlist_visible {
            get {
                return ((global::System.Windows.Visibility)(this["playlist_visible"]));
            }
            set {
                this["playlist_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public global::System.Windows.GridLength gridsplitter_width {
            get {
                return ((global::System.Windows.GridLength)(this["gridsplitter_width"]));
            }
            set {
                this["gridsplitter_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string volume_value {
            get {
                return ((string)(this["volume_value"]));
            }
            set {
                this["volume_value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool shuffle {
            get {
                return ((bool)(this["shuffle"]));
            }
            set {
                this["shuffle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_play_next_in_folder {
            get {
                return ((bool)(this["auto_play_next_in_folder"]));
            }
            set {
                this["auto_play_next_in_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int key_volume_up {
            get {
                return ((int)(this["key_volume_up"]));
            }
            set {
                this["key_volume_up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int key_volume_down {
            get {
                return ((int)(this["key_volume_down"]));
            }
            set {
                this["key_volume_down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool aspect_zoom {
            get {
                return ((bool)(this["aspect_zoom"]));
            }
            set {
                this["aspect_zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool aspect_normal {
            get {
                return ((bool)(this["aspect_normal"]));
            }
            set {
                this["aspect_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ml_col_span {
            get {
                return ((int)(this["ml_col_span"]));
            }
            set {
                this["ml_col_span"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Uniform")]
        public global::System.Windows.Media.Stretch ml_aspect {
            get {
                return ((global::System.Windows.Media.Stretch)(this["ml_aspect"]));
            }
            set {
                this["ml_aspect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ml_always_on_top {
            get {
                return ((bool)(this["ml_always_on_top"]));
            }
            set {
                this["ml_always_on_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool expanded {
            get {
                return ((bool)(this["expanded"]));
            }
            set {
                this["expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ml_row_span {
            get {
                return ((int)(this["ml_row_span"]));
            }
            set {
                this["ml_row_span"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush component_state_flag_background {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["component_state_flag_background"]));
            }
            set {
                this["component_state_flag_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visible")]
        public global::System.Windows.Visibility component_state_flag_visibility {
            get {
                return ((global::System.Windows.Visibility)(this["component_state_flag_visibility"]));
            }
            set {
                this["component_state_flag_visibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1")]
        public global::System.Windows.Thickness main_border_thickness {
            get {
                return ((global::System.Windows.Thickness)(this["main_border_thickness"]));
            }
            set {
                this["main_border_thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush main_border_background {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["main_border_background"]));
            }
            set {
                this["main_border_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ml_always_on_top_when_playing {
            get {
                return ((bool)(this["ml_always_on_top_when_playing"]));
            }
            set {
                this["ml_always_on_top_when_playing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool aspect_stretch {
            get {
                return ((bool)(this["aspect_stretch"]));
            }
            set {
                this["aspect_stretch"] = value;
            }
        }
    }
}
